### ISSUE TITLE
Difficulty on building electron app

### ISSUE THREAD

**Issue by CottageCabbage** [CottageCabbage/vu-dooit#41]
running the command `npm run electron:build`, which on package.json's script is as `quasar build -m electron` returns the following:

```bash
 App •  WAIT  • Bundling app with electron-packager...
/home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:130
            electronVersion: getPackageJson('electron').version
                                                       ^

TypeError: Cannot read properties of undefined (reading 'version')
    at /home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:130:56
    at new Promise (<anonymous>)
    at /home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:124:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ElectronBuilder.build (/home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:23:7)
```

There's more before this, but that's what producing the error though

**Comment by CottageCabbage** [comment]
Changing `electron.bundler` to 'builder' at quasar.config.js just switches an error to another: 

```bash
 App •  WAIT  • Bundling app with electron-builder...
/home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:132
          : bundler.build(bundlerConfig)
                    ^

TypeError: Cannot read properties of undefined (reading 'build')
    at /home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:132:21
    at new Promise (<anonymous>)
    at /home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:124:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ElectronBuilder.build (/home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:23:7)
```

**Comment by CottageCabbage** [comment]
With packager as bundler, after including Electron on dependencies, deleting node_modules and running `npm install`, the following error pops up.

```
 App •  WAIT  • Bundling app with electron-packager...
/home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:128
          ? bundler({
            ^

TypeError: bundler is not a function
    at /home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:128:13
    at new Promise (<anonymous>)
    at /home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:124:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ElectronBuilder.build (/home/cottagecabbage/Desktop/Dev/vu-dooit/node_modules/@quasar/app-vite/lib/modes/electron/electron-builder.js:23:7)

Node.js v18.0.0
```

Found issues about it, and it seems like deleting node_modules and running npm install should be the solution, but that doesn't seem to be working, I've tried.

**Comment by CottageCabbage** [comment]
Been testing things out and the problem seems to be linked with the Vite option of `npm init quasar`. I couldn't solve it in the end. Sucks, since Vite is kind of better, but will have to remake Vu-dooit with Webpack. Shouldn't take long since it's just copying files from one place to another, but yeah :|

Big sad
